2023-06-16 23:06:57,983 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-16 23:07:01,089 [INFO] shopapp.views: Rendering shop index
2023-06-16 23:07:01,816 [INFO] shopapp.views: Rendering shop index
2023-06-16 23:07:09,556 [INFO] shopapp.views: Rendering shop index
2023-06-16 23:07:09,658 [INFO] shopapp.views: Rendering shop index
2023-06-16 23:09:34,950 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-16 23:10:00,526 [INFO] shopapp.views: Rendering shop index
2023-06-16 23:10:00,637 [INFO] shopapp.views: Rendering shop index
2023-06-16 23:10:00,792 [INFO] shopapp.views: Rendering shop index
2023-06-16 23:10:00,988 [INFO] shopapp.views: Rendering shop index
2023-06-17 16:17:54,882 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-17 16:18:08,246 [INFO] shopapp.views: Rendering shop index
2023-06-17 16:18:09,872 [WARNING] django.request: Not Found: /favicon.ico
2023-06-25 15:00:51,261 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 15:01:20,775 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\http\request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
2023-06-25 15:01:21,074 [WARNING] django.request: Bad Request: /ru/shop/
2023-06-25 15:01:22,511 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\http\request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
2023-06-25 15:01:22,574 [WARNING] django.request: Bad Request: /favicon.ico
2023-06-25 15:01:48,649 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\mysite\settings.py changed, reloading.
2023-06-25 15:01:51,166 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 15:01:55,403 [INFO] shopapp.views: Rendering shop index
2023-06-25 15:01:59,684 [WARNING] django.request: Not Found: /favicon.ico
2023-06-25 15:06:57,512 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 15:07:10,864 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-06-25 15:07:14,558 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 15:07:35,599 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-06-25 15:07:40,221 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 15:07:54,891 [ERROR] django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 190, in get
    name = elem["naem"]
KeyError: 'naem'
2023-06-25 15:14:48,519 [INFO] django.utils.autoreload: C:\Users\Acer\AppData\Local\Programs\Python\Python39\Lib\site-packages\urllib3\connectionpool.py changed, reloading.
2023-06-25 15:14:51,774 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 15:15:57,940 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\mysite\settings.py changed, reloading.
2023-06-25 15:16:03,738 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 15:16:54,023 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\mysite\settings.py changed, reloading.
2023-06-25 15:17:02,749 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-06-25 15:17:22,576 [WARNING] django.request: Not Found: /ru/shop/products/export.
2023-06-25 15:17:28,378 [ERROR] django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 190, in get
    name = elem["naem"]
KeyError: 'naem'
2023-06-25 15:19:12,015 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-06-25 15:19:15,719 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 11:58:31,837 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 11:58:33,723 [INFO] shopapp.views: Rendering shop index
2023-07-08 11:58:36,539 [WARNING] django.request: Not Found: /favicon.ico
2023-07-08 12:03:07,515 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:03:12,819 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:03:20,094 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:03:24,137 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:03:29,558 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/product/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\admin\templatetags\admin_modify.py", line 65, in submit_row
    add = context["add"]
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'add'
2023-07-08 12:03:56,647 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/product/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'import_product_csv' not found. 'import_product_csv' is not a valid view function or pattern name.
2023-07-08 12:08:29,472 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:08:39,964 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:08:59,454 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:09:04,961 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:09:11,502 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:09:16,361 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:09:35,878 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:09:43,408 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:09:49,704 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:09:56,248 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:10:08,539 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:10:15,443 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:10:32,702 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:10:40,475 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:10:51,670 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:10:58,819 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:11:08,169 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:11:14,881 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:11:21,462 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:11:26,026 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:11:31,063 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:11:36,591 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:11:48,515 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:11:52,437 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:12:00,895 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:12:06,106 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:12:17,775 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:12:23,825 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:12:40,668 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:12:46,340 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:12:57,426 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:13:02,548 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:13:12,386 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:13:18,323 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:13:32,144 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:13:37,529 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:13:43,237 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:13:48,415 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:13:57,794 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:14:02,829 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:14:16,850 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:14:22,986 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:14:34,592 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:14:40,255 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:14:43,819 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:14:49,691 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:15:17,511 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/product/import-products-csv/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py", line 98, in import_csv
    products.objects.bulk_create(products)
AttributeError: 'list' object has no attribute 'objects'
2023-07-08 12:15:45,859 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:15:50,144 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:30:34,168 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:30:40,251 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:31:07,731 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:31:15,397 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:31:52,298 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:31:57,779 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:32:37,491 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:32:44,306 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:32:59,841 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:33:06,968 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:33:14,252 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:33:19,440 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:34:09,413 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:34:15,364 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:34:36,594 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:34:45,628 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:34:53,647 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:34:59,249 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:35:17,374 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:35:21,578 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:35:39,302 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:35:48,144 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:35:55,444 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:36:01,685 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:36:27,638 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:36:33,146 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:36:48,699 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:36:54,501 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:37:11,638 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:37:18,297 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:37:29,416 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:37:35,101 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:37:46,228 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:37:52,095 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:38:19,743 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:38:25,361 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:38:32,487 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:38:40,616 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:38:45,960 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:38:49,222 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:38:59,332 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:39:06,250 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:39:17,022 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 12:39:22,128 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:43:04,514 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:43:11,424 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:43:30,363 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:43:37,390 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:43:49,319 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:43:55,781 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:44:11,587 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:44:17,550 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:44:40,975 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:44:46,106 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:44:53,723 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:45:01,723 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:45:10,549 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:45:17,750 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:46:23,554 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 12:46:28,568 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:52:12,229 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py changed, reloading.
2023-07-08 12:52:16,393 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 12:52:26,109 [WARNING] django.request: Method Not Allowed: /ru/shop/api/products/upload_csv/
2023-07-08 12:52:47,190 [WARNING] django.request: Method Not Allowed: /ru/shop/api/products/upload_csv/
2023-07-08 13:31:49,384 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\models.py changed, reloading.
2023-07-08 13:31:56,599 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 13:32:05,881 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\models.py changed, reloading.
2023-07-08 13:32:11,648 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 13:32:18,236 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\models.py changed, reloading.
2023-07-08 13:32:22,571 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 13:32:30,277 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\models.py changed, reloading.
2023-07-08 13:32:34,030 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 13:32:42,652 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\models.py changed, reloading.
2023-07-08 13:32:46,698 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 13:32:58,344 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\models.py changed, reloading.
2023-07-08 13:33:01,708 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 13:39:55,053 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 13:40:48,865 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 13:41:33,219 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 13:41:36,977 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 13:41:54,071 [ERROR] django.request: Internal Server Error: /ru/blog/articles_video/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: blogapp/articlevideo_list.html
2023-07-08 13:46:19,100 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\urls.py changed, reloading.
2023-07-08 13:46:25,422 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 13:48:11,496 [ERROR] django.request: Internal Server Error: /ru/blog/articles_video/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: blogapp/articlevideo_list.html
2023-07-08 13:48:50,622 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 13:48:54,959 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 13:48:58,186 [ERROR] django.request: Internal Server Error: /ru/blog/articles_video/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: article_video_list.html, blogapp/articlevideo_list.html
2023-07-08 13:49:29,385 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 13:49:33,782 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 13:49:38,781 [ERROR] django.request: Internal Server Error: /ru/blog/articles_video/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
2023-07-08 13:50:25,698 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\admin.py changed, reloading.
2023-07-08 13:50:30,813 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 13:50:40,791 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\admin.py changed, reloading.
2023-07-08 13:50:44,611 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 13:50:55,766 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\admin.py changed, reloading.
2023-07-08 13:50:59,981 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 13:51:07,821 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\admin.py changed, reloading.
2023-07-08 13:51:11,631 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 13:51:25,944 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\admin.py changed, reloading.
2023-07-08 13:51:30,164 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 13:54:22,252 [ERROR] django.request: Internal Server Error: /ru/blog/article_video/1/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: blogapp/articlevideo_detail.html
2023-07-08 14:01:45,490 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:01:52,888 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:02:01,633 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:02:08,635 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:02:22,484 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:02:27,838 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:02:37,945 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:02:44,751 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:02:50,544 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:02:56,876 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:03:09,881 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:03:15,876 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:03:23,010 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:03:27,866 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:03:33,329 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:03:38,180 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:03:42,315 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:03:46,423 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:03:54,435 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:04:03,830 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:04:15,880 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:04:21,107 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:04:26,239 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:04:30,711 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:04:37,317 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:04:43,074 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:04:47,281 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:04:52,217 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:05:05,279 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:05:10,294 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:05:18,923 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:05:24,181 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:05:39,680 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:05:44,095 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:05:49,783 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:05:54,148 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:05:58,501 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:06:03,769 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:06:10,714 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:06:16,333 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:06:35,650 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:06:43,022 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:06:54,139 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:06:58,715 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:07:22,317 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:07:27,701 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:07:51,411 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\urls.py changed, reloading.
2023-07-08 14:07:56,504 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:08:28,545 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\urls.py changed, reloading.
2023-07-08 14:08:33,135 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:08:37,038 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\urls.py changed, reloading.
2023-07-08 14:08:41,985 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:09:04,711 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\urls.py changed, reloading.
2023-07-08 14:09:08,275 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:09:10,939 [WARNING] django.request: Not Found: /ru/blog/article_video/latest_feed
2023-07-08 14:09:16,517 [WARNING] django.request: Not Found: /ru/blog/article_video/latest_feed/
2023-07-08 14:32:07,565 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\models.py changed, reloading.
2023-07-08 14:32:14,679 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:32:23,857 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\models.py changed, reloading.
2023-07-08 14:32:28,869 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:32:35,136 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\models.py changed, reloading.
2023-07-08 14:32:39,119 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:32:47,647 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\models.py changed, reloading.
2023-07-08 14:32:51,844 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:33:06,615 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\models.py changed, reloading.
2023-07-08 14:33:10,587 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:33:23,647 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\models.py changed, reloading.
2023-07-08 14:33:30,328 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:33:48,923 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\views.py changed, reloading.
2023-07-08 14:33:53,434 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:35:44,038 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\mysite\urls.py changed, reloading.
2023-07-08 14:35:50,023 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:36:12,256 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\mysite\urls.py changed, reloading.
2023-07-08 14:36:17,917 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:36:30,519 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\mysite\urls.py changed, reloading.
2023-07-08 14:36:38,079 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:36:48,514 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\mysite\urls.py changed, reloading.
2023-07-08 14:36:53,344 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:37:52,116 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\mysite\sitemaps.py changed, reloading.
2023-07-08 14:37:56,073 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:37:59,111 [WARNING] django.request: Not Found: /ru/sitemap.xml/
2023-07-08 14:38:38,346 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\mysite\settings.py changed, reloading.
2023-07-08 14:38:47,377 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:38:48,901 [WARNING] django.request: Not Found: /ru/sitemap.xml/
2023-07-08 14:39:34,235 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\mysite\urls.py changed, reloading.
2023-07-08 14:39:38,686 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:39:41,975 [ERROR] django.request: Internal Server Error: /ru/sitemap.xml/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\views.py", line 34, in inner
    response = func(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\views.py", line 128, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\__init__.py", line 163, in get_urls
    return self._urls(page, protocol, domain)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\__init__.py", line 183, in _urls
    loc = f"{protocol}://{domain}{self._location(item)}"
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\__init__.py", line 118, in _location
    return self._get("location", item)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\__init__.py", line 92, in _get
    return attr(item)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\__init__.py", line 128, in location
    return item.get_absolute_url()
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\models.py", line 32, in get_absolute_url
    return reverse("blogapp:articles_video", kwargs={"pk": self.pk})
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'articles_video' with keyword arguments '{'pk': 3}' not found. 1 pattern(s) tried: ['ru/blog/articles_video/\\Z']
2023-07-08 14:40:41,610 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\models.py changed, reloading.
2023-07-08 14:40:41,853 [ERROR] django.request: Internal Server Error: /ru/sitemap.xml/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\views.py", line 34, in inner
    response = func(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\views.py", line 128, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\__init__.py", line 163, in get_urls
    return self._urls(page, protocol, domain)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\__init__.py", line 183, in _urls
    loc = f"{protocol}://{domain}{self._location(item)}"
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\__init__.py", line 118, in _location
    return self._get("location", item)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\__init__.py", line 92, in _get
    return attr(item)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\__init__.py", line 128, in location
    return item.get_absolute_url()
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\models.py", line 32, in get_absolute_url
    return reverse("blogapp:articles_detail", kwargs={"pk": self.pk})
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'articles_video' with keyword arguments '{'pk': 3}' not found. 1 pattern(s) tried: ['ru/blog/articles_video/\\Z']
2023-07-08 14:40:45,026 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:40:48,190 [ERROR] django.request: Internal Server Error: /ru/sitemap.xml/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\views.py", line 34, in inner
    response = func(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\views.py", line 128, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\__init__.py", line 163, in get_urls
    return self._urls(page, protocol, domain)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\__init__.py", line 183, in _urls
    loc = f"{protocol}://{domain}{self._location(item)}"
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\__init__.py", line 118, in _location
    return self._get("location", item)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\__init__.py", line 92, in _get
    return attr(item)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\sitemaps\__init__.py", line 128, in location
    return item.get_absolute_url()
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\models.py", line 32, in get_absolute_url
    return reverse("blogapp:articles_detail", kwargs={"pk": self.pk})
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'articles_detail' not found. 'articles_detail' is not a valid view function or pattern name.
2023-07-08 14:41:08,560 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\models.py changed, reloading.
2023-07-08 14:41:12,961 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:43:43,904 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\models.py changed, reloading.
2023-07-08 14:43:47,315 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:46:38,235 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\mysite\sitemaps.py changed, reloading.
2023-07-08 14:46:42,134 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:47:33,234 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\blogapp\urls.py changed, reloading.
2023-07-08 14:47:36,368 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:51:35,894 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 14:51:39,606 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:52:37,457 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\urls.py changed, reloading.
2023-07-08 14:52:40,169 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 14:57:08,483 [ERROR] django.request: Internal Server Error: /ru/shop/products/latest/feed/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\syndication\views.py", line 40, in __call__
    feedgen = self.get_feed(obj, request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\syndication\views.py", line 143, in get_feed
    link = add_domain(current_site.domain, link, request.is_secure())
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\syndication\views.py", line 17, in add_domain
    if url.startswith("//"):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\functional.py", line 149, in __wrapper__
    res = func(*self.__args, **self.__kw)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'products' not found. 'products' is not a valid view function or pattern name.
2023-07-08 14:58:13,919 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-08 14:58:19,165 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 18:22:15,527 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 18:22:23,338 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 18:26:46,112 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 18:26:51,823 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 18:26:55,324 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/order/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\templates.py", line 74, in rendered_content
    return real_rendered_content.fget(self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'import_orders_csv' not found. 'import_orders_csv' is not a valid view function or pattern name.
2023-07-08 18:27:11,913 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 18:27:15,388 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 18:33:16,634 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/order/import-orders-csv/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py", line 138, in import_csv
    csv_file = save_csv_orders(
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py", line 29, in save_csv_orders
    orders = [
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py", line 30, in <listcomp>
    Order(**row)
TypeError: keywords must be strings
2023-07-08 18:33:38,512 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/order/import-orders-csv/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py", line 138, in import_csv
    csv_file = save_csv_orders(
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py", line 29, in save_csv_orders
    orders = [
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py", line 30, in <listcomp>
    Order(**row)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\fields\related_descriptors.py", line 237, in __set__
    raise ValueError(
ValueError: Cannot assign "'1'": "Order.user" must be a "User" instance.
2023-07-08 18:33:43,097 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/order/import-orders-csv/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py", line 138, in import_csv
    csv_file = save_csv_orders(
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py", line 29, in save_csv_orders
    orders = [
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py", line 30, in <listcomp>
    Order(**row)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\fields\related_descriptors.py", line 237, in __set__
    raise ValueError(
ValueError: Cannot assign "'1'": "Order.user" must be a "User" instance.
2023-07-08 18:34:45,870 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/order/import-orders-csv/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py", line 138, in import_csv
    csv_file = save_csv_orders(
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py", line 29, in save_csv_orders
    orders = [
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py", line 30, in <listcomp>
    Order(**row)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\fields\related_descriptors.py", line 237, in __set__
    raise ValueError(
ValueError: Cannot assign "'admin'": "Order.user" must be a "User" instance.
2023-07-08 18:35:43,344 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 18:35:50,135 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 18:36:02,522 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/order/import-orders-csv/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py", line 125, in import_csv
    print(Order.user.all())
AttributeError: 'ForwardManyToOneDescriptor' object has no attribute 'all'
2023-07-08 18:36:17,372 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py changed, reloading.
2023-07-08 18:36:22,533 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 18:36:27,191 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/order/import-orders-csv/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py", line 139, in import_csv
    csv_file = save_csv_orders(
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py", line 29, in save_csv_orders
    orders = [
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py", line 30, in <listcomp>
    Order(**row)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\base.py", line 541, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\fields\related_descriptors.py", line 237, in __set__
    raise ValueError(
ValueError: Cannot assign "'admin'": "Order.user" must be a "User" instance.
2023-07-08 18:37:25,648 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/order/import-orders-csv/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py", line 139, in import_csv
    csv_file = save_csv_orders(
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py", line 29, in save_csv_orders
    orders = [
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py", line 30, in <listcomp>
    Order(**row)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\base.py", line 562, in __init__
    _setattr(self, prop, value)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\fields\related_descriptors.py", line 597, in __set__
    raise TypeError(
TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use products.set() instead.
2023-07-08 18:39:11,277 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py changed, reloading.
2023-07-08 18:39:14,910 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 18:39:17,746 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/order/import-orders-csv/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py", line 139, in import_csv
    csv_file = save_csv_orders(
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py", line 29, in save_csv_orders
    orders = [
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py", line 30, in <listcomp>
    Order(**row)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\base.py", line 562, in __init__
    _setattr(self, prop, value)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\fields\related_descriptors.py", line 597, in __set__
    raise TypeError(
TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use products.set() instead.
2023-07-08 18:39:53,409 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py changed, reloading.
2023-07-08 18:39:57,665 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 18:40:08,039 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/order/import-orders-csv/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\admin.py", line 139, in import_csv
    csv_file = save_csv_orders(
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py", line 30, in save_csv_orders
    orders = [
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py", line 31, in <listcomp>
    Order(**row)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\base.py", line 562, in __init__
    _setattr(self, prop, value)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\fields\related_descriptors.py", line 597, in __set__
    raise TypeError(
TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use products.set() instead.
2023-07-08 18:40:41,963 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py changed, reloading.
2023-07-08 18:40:45,411 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 18:42:59,869 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py changed, reloading.
2023-07-08 18:43:02,952 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-08 18:44:15,078 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\common.py changed, reloading.
2023-07-08 18:44:19,688 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:01:20,666 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:01:33,461 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:01:34,309 [WARNING] django.request: Not Found: /favicon.ico
2023-07-09 15:24:14,734 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\mysite\settings.py changed, reloading.
2023-07-09 15:24:20,985 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:24:54,689 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\myauth\views.py changed, reloading.
2023-07-09 15:25:01,175 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:25:21,495 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\myauth\views.py changed, reloading.
2023-07-09 15:25:26,746 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:25:45,034 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\myauth\views.py changed, reloading.
2023-07-09 15:25:50,235 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:25:58,913 [WARNING] django.request: Not Found: /ru/
2023-07-09 15:26:09,196 [WARNING] django.request: Not Found: /ru/accounts/cookie/
2023-07-09 15:27:02,260 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\myauth\views.py changed, reloading.
2023-07-09 15:27:09,817 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:27:17,956 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\myauth\views.py changed, reloading.
2023-07-09 15:27:22,864 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:27:30,897 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\myauth\views.py changed, reloading.
2023-07-09 15:27:36,979 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:28:40,340 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\urls.py changed, reloading.
2023-07-09 15:28:46,194 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:28:57,442 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\urls.py changed, reloading.
2023-07-09 15:29:01,431 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:29:13,300 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\urls.py changed, reloading.
2023-07-09 15:29:17,959 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:29:45,440 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:33:02,455 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 15:33:11,616 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:33:25,353 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 15:33:31,090 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:33:40,407 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 15:33:43,773 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:33:58,825 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 15:34:03,723 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:34:25,173 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 15:34:31,980 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:34:39,708 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 15:34:43,805 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:34:45,755 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:35:12,333 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 15:35:20,076 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:36:06,685 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 15:36:13,505 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:37:36,929 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\urls.py changed, reloading.
2023-07-09 15:37:43,183 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:37:50,472 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:52:06,866 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 15:52:17,556 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 15:53:38,538 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:53:42,600 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:53:43,309 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:53:43,892 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:53:44,447 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:53:44,907 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:53:45,363 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:53:45,798 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:53:46,128 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:55:05,676 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:55:06,436 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:55:07,160 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:55:07,832 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:55:08,412 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:55:09,076 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:55:10,967 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:55:11,643 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:55:16,259 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:55:19,323 [INFO] shopapp.views: Rendering shop index
2023-07-09 15:55:19,972 [INFO] shopapp.views: Rendering shop index
2023-07-09 16:27:42,300 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 16:27:50,044 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 16:28:21,621 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 16:28:27,344 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 16:28:48,994 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 16:28:53,787 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 16:29:02,374 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 16:29:10,179 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 16:29:19,879 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 16:29:26,093 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 16:29:46,799 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 16:29:55,007 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 16:30:04,352 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 16:30:08,634 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 16:30:19,062 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 16:30:28,611 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 16:32:55,037 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\mysite\settings.py changed, reloading.
2023-07-09 17:15:36,239 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:15:40,008 [WARNING] django.request: Not Found: /ru/shop/users/
2023-07-09 17:15:54,418 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'pk'
2023-07-09 17:17:05,958 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:17:12,276 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:20:35,327 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:20:39,240 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:22:31,851 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got multiple values for argument 'pk'
2023-07-09 17:23:05,722 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:23:11,308 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:23:14,649 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'pk'
2023-07-09 17:23:43,245 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:23:49,624 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:23:52,763 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view shopapp.views.view didn't return an HttpResponse object. It returned None instead.
2023-07-09 17:24:24,777 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:24:28,601 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:24:31,904 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view shopapp.views.view didn't return an HttpResponse object. It returned None instead.
2023-07-09 17:26:09,733 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:26:15,007 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:26:18,342 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'pk'
2023-07-09 17:26:35,231 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'pk'
2023-07-09 17:26:35,354 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:26:38,971 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:26:56,848 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:27:01,747 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:27:29,810 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:27:35,522 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:27:49,962 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:27:53,466 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:27:57,608 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 196, in get
    return render(request, "shopapp/user_orders.html", context=context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\templates.py", line 96, in render
    return real_render(request, template_name, context, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 57, in render
    context = make_context(
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\context.py", line 278, in make_context
    raise TypeError(
TypeError: context must be a dict rather than QuerySet.
2023-07-09 17:28:20,475 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:28:24,260 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:31:20,360 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'product'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 196, in get
    return render(request, "shopapp/user_orders.html", context=context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\templates.py", line 96, in render
    return real_render(request, template_name, context, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 16: 'product', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
2023-07-09 17:31:48,514 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 196, in get
    return render(request, "shopapp/user_orders.html", context=context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\templates.py", line 96, in render
    return real_render(request, template_name, context, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 193, in render
    values = list(values)
TypeError: 'ManyRelatedManager' object is not iterable
2023-07-09 17:31:58,186 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 196, in get
    return render(request, "shopapp/user_orders.html", context=context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\templates.py", line 96, in render
    return real_render(request, template_name, context, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 193, in render
    values = list(values)
TypeError: 'ManyRelatedManager' object is not iterable
2023-07-09 17:36:32,648 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 196, in get
    return render(request, "shopapp/user_orders.html", context=context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\templates.py", line 96, in render
    return real_render(request, template_name, context, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 484, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '()' from 'order.products.all()'
2023-07-09 17:42:42,677 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:42:55,364 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:43:39,562 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:43:43,451 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:44:45,144 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:44:48,897 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:46:04,636 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:46:08,642 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:49:18,457 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:49:24,389 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:49:27,660 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 195, in get
    user_info = self.get_context_data(pk)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 201, in get_context_data
    print(user_info.username)
AttributeError: 'QuerySet' object has no attribute 'username'
2023-07-09 17:49:56,633 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 195, in get
    user_info = self.get_context_data(pk)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 201, in get_context_data
    print(user_info.username)
AttributeError: 'QuerySet' object has no attribute 'username'
2023-07-09 17:49:57,169 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:50:01,430 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:50:07,575 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 195, in get
    user_info = self.get_context_data(pk)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 200, in get_context_data
    user_info = User.objects.filter(pk=pk).fetchone()
AttributeError: 'QuerySet' object has no attribute 'fetchone'
2023-07-09 17:50:27,221 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 195, in get
    user_info = self.get_context_data(pk)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 200, in get_context_data
    user_info = User.objects.filter(pk=pk)
AttributeError: 'QuerySet' object has no attribute 'fetchone'
2023-07-09 17:50:27,551 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:50:30,950 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:50:34,636 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 195, in get
    user_info = self.get_context_data(pk)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 201, in get_context_data
    print(user_info.keys())
AttributeError: 'QuerySet' object has no attribute 'keys'
2023-07-09 17:51:41,403 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:51:47,436 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:52:56,526 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:53:03,200 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:54:34,648 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 17:54:39,065 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 17:57:05,611 [WARNING] django.request: Not Found: /ru/account/about-me/
2023-07-09 17:59:56,263 [ERROR] django.request: Internal Server Error: /ru/shop/users/3/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 195, in get
    username = self.get_context_data(pk)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 201, in get_context_data
    return user_info.get()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
2023-07-09 18:00:11,583 [ERROR] django.request: Internal Server Error: /ru/shop/users/3/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 195, in get
    username = self.get_context_data(pk)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 201, in get_context_data
    return user_info.get()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
2023-07-09 18:00:12,471 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 18:00:17,279 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:00:21,274 [ERROR] django.request: Internal Server Error: /ru/shop/users/3/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 195, in get
    username = self.get_context_data(pk)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 201, in get_context_data
    return user_info.get()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
2023-07-09 18:00:26,934 [ERROR] django.request: Internal Server Error: /ru/shop/users/3/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 195, in get
    username = self.get_context_data(pk)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 201, in get_context_data
    return user_info.get()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
2023-07-09 18:00:36,484 [ERROR] django.request: Internal Server Error: /ru/shop/users/3/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 195, in get
    username = self.get_context_data(pk)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 201, in get_context_data
    return user_info.get()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
2023-07-09 18:04:23,384 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 18:04:28,568 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:04:32,102 [ERROR] django.request: Internal Server Error: /ru/shop/users/3/orders/
Traceback (most recent call last):
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 198, in get
    username = self.get_context_data(pk)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 206, in get_context_data
    return user_info.get()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 199, in get
    except django.contrib.auth.models.User.DoesNotExists:
AttributeError: type object 'User' has no attribute 'DoesNotExists'
2023-07-09 18:05:08,974 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 18:05:13,208 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:06:11,088 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 18:06:15,756 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:06:18,890 [ERROR] django.request: Internal Server Error: /ru/shop/users/3/orders/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\middleware.py", line 175, in __call__
    return f(*args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\debug_toolbar\middleware.py", line 69, in __call__
    panel.generate_stats(request, response)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\debug_toolbar\panels\headers.py", line 49, in generate_stats
    self.response_headers = dict(sorted(response.items()))
AttributeError: type object 'Http404' has no attribute 'items'
2023-07-09 18:08:07,767 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 18:08:13,604 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:08:15,570 [WARNING] django.request: Not Found: /ru/shop/users/3/orders/
2023-07-09 18:08:23,832 [WARNING] django.request: Not Found: /ru/shop/users/1/orders/
2023-07-09 18:10:16,772 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\urls.py changed, reloading.
2023-07-09 18:10:20,485 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:12:11,414 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 18:12:15,146 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:14:10,778 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 18:14:17,519 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:14:35,913 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\urls.py changed, reloading.
2023-07-09 18:14:39,122 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:14:44,335 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'user_id'
2023-07-09 18:15:42,454 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 18:15:48,058 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:15:51,540 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'user_id'
2023-07-09 18:16:14,976 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'user_id'
2023-07-09 18:16:17,125 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'user_id'
2023-07-09 18:17:15,306 [ERROR] django.request: Internal Server Error: /ru/shop/users/1/orders/export/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'user_id'
2023-07-09 18:17:15,628 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\urls.py changed, reloading.
2023-07-09 18:17:19,561 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:18:21,014 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 18:18:26,142 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:18:55,749 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 18:19:00,612 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:19:30,567 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 18:19:34,132 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:19:48,504 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 18:19:52,135 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:20:14,711 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 18:20:18,137 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:20:26,262 [ERROR] django.request: Internal Server Error: /ru/shop/users/3/orders/export/
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py", line 214, in get
    print(user_info.get())
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
2023-07-09 18:20:52,947 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 18:20:56,798 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:20:58,813 [WARNING] django.request: Not Found: /ru/shop/users/3/orders/export/
2023-07-09 18:22:54,352 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 18:22:58,621 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:25:39,446 [WARNING] django.request: Not Found: /ru/shop/users/3/orders/export/
2023-07-09 18:26:31,595 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 18:26:36,290 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:26:52,937 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 18:26:56,310 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-09 18:27:35,856 [INFO] django.utils.autoreload: C:\PycharmProjects\python_django\REST\M_11_Files\mysite\shopapp\views.py changed, reloading.
2023-07-09 18:27:40,068 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-08-22 15:54:18,538 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-08-22 15:54:45,950 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-08-22 15:55:05,888 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
